-- Name and Info of Menbers
insert into membro VALUES('Gonçalo','g@hotmail.com',2002);
insert into membro VALUES('Maria','maria@gmail.pt',2001);
insert into membro VALUES('Leonor','leonor@yahoo.org',1976);
insert into membro VALUES('Guilherme','gui@alunos.uevora.pt',1986);
insert into membro VALUES('Silvia','silvia@frusoal.pt',1976);
insert into membro VALUES('Ricardo','ricardo@eva.motorista.pt',1978);
insert into membro VALUES('Patricia','Pat@live.com.pt',1998);
insert into membro VALUES('Helder','Hell@yahoo.com',1999);
insert into membro VALUES('Daniela','daniela@risco.fidelidade.pt',1999);
insert into membro VALUES('Sandra','sandra.gestora@santander.com',1975);
insert into membro VALUES('Carlos','carlos@piloto.tap.com',1967);
insert into membro VALUES('andre','andre@it.siva.com',1995);
insert into membro VALUES('Visa','visa@algarmanta.pt', 1981);
insert into membro VALUES('Susana','susana@mar&sol.pt',1987);
insert into membro VALUES('Ilidio','ilidio@rentaprtmr.pt',1986);
--Member Gonçalo likes
INSERT INTO gostade VALUES('Gonçalo','Albânia');
INSERT INTO gostade VALUES('Gonçalo','Alemanha');
INSERT INTO gostade VALUES('Gonçalo','Andorra');
INSERT INTO gostade VALUES('Gonçalo','Armênia');
INSERT INTO gostade VALUES('Gonçalo','Áustria');
INSERT INTO gostade VALUES('Gonçalo','Bélgica');
INSERT INTO gostade VALUES('Gonçalo','Bielorrúsia');
INSERT INTO gostade VALUES('Gonçalo','Bósnia e Herzegovina');
INSERT INTO gostade VALUES('Gonçalo','Bulgária');
INSERT INTO gostade VALUES('Gonçalo','Chipre');
INSERT INTO gostade VALUES('Gonçalo','Croátia');
INSERT INTO gostade VALUES('Gonçalo','Dinamarca');
INSERT INTO gostade VALUES('Gonçalo','Eslováquia');
INSERT INTO gostade VALUES('Gonçalo','Eslovênia');
INSERT INTO gostade VALUES('Gonçalo','Espanha');
INSERT INTO gostade VALUES('Gonçalo','Estônia');
INSERT INTO gostade VALUES('Gonçalo','Filândia');
INSERT INTO gostade VALUES('Gonçalo','França');
INSERT INTO gostade VALUES('Gonçalo','Grécia');
INSERT INTO gostade VALUES('Gonçalo','Hungria');
INSERT INTO gostade VALUES('Gonçalo','Irlanda');
INSERT INTO gostade VALUES('Gonçalo','Islândia');
INSERT INTO gostade VALUES('Gonçalo','Itália');
INSERT INTO gostade VALUES('Gonçalo','Letônia');
INSERT INTO gostade VALUES('Gonçalo','Liechtenstein');
INSERT INTO gostade VALUES('Gonçalo','Lituânia');
INSERT INTO gostade VALUES('Gonçalo','Luxemburgo');
INSERT INTO gostade VALUES('Gonçalo','Malta');
INSERT INTO gostade VALUES('Gonçalo','Moldávia');
INSERT INTO gostade VALUES('Gonçalo','Mônaco');
INSERT INTO gostade VALUES('Gonçalo','Montenegro');
INSERT INTO gostade VALUES('Gonçalo','Noruega');
INSERT INTO gostade VALUES('Gonçalo','Países Baixos');
INSERT INTO gostade VALUES('Gonçalo','Polônia');
INSERT INTO gostade VALUES('Gonçalo','Portugal');
INSERT INTO gostade VALUES('Gonçalo','República Checa');
INSERT INTO gostade VALUES('Gonçalo','Macedônia do Norte');
INSERT INTO gostade VALUES('Gonçalo','Irlanda do Norte');
INSERT INTO gostade VALUES('Gonçalo','Inglaterra');
INSERT INTO gostade VALUES('Gonçalo','Escócia');
INSERT INTO gostade VALUES('Gonçalo','País de Gales');
INSERT INTO gostade VALUES('Gonçalo','Romênia');
INSERT INTO gostade VALUES('Gonçalo','Rússia');
INSERT INTO gostade VALUES('Gonçalo','San Marinho');
INSERT INTO gostade VALUES('Gonçalo','Sérvia');
INSERT INTO gostade VALUES('Gonçalo','Suécia');
INSERT INTO gostade VALUES('Gonçalo','Suíça');
INSERT INTO gostade VALUES('Gonçalo','Turquia');
INSERT INTO gostade VALUES('Gonçalo','Ucrânia');
INSERT INTO gostade VALUES('Gonçalo','Vaticano');
-- Maria likes
INSERT INTO gostade VALUES('Maria','Albânia');
INSERT INTO gostade VALUES('Maria','Alemanha');
INSERT INTO gostade VALUES('Maria','Andorra');
INSERT INTO gostade VALUES('Maria','Armênia');
INSERT INTO gostade VALUES('Maria','Áustria');
INSERT INTO gostade VALUES('Maria','Bélgica');
INSERT INTO gostade VALUES('Maria','Bielorrúsia');
INSERT INTO gostade VALUES('Maria','Bósnia e Herzegovina');
INSERT INTO gostade VALUES('Maria','Bulgária');
INSERT INTO gostade VALUES('Maria','Chipre');
INSERT INTO gostade VALUES('Maria','Croátia');
INSERT INTO gostade VALUES('Maria','Dinamarca');
INSERT INTO gostade VALUES('Maria','Eslováquia');
INSERT INTO gostade VALUES('Maria','Eslovênia');
INSERT INTO gostade VALUES('Maria','Espanha');
INSERT INTO gostade VALUES('Maria','Estônia');
INSERT INTO gostade VALUES('Maria','Filândia');
INSERT INTO gostade VALUES('Maria','França');
INSERT INTO gostade VALUES('Maria','Grécia');
INSERT INTO gostade VALUES('Maria','Hungria');
INSERT INTO gostade VALUES('Maria','Irlanda');
INSERT INTO gostade VALUES('Maria','Islândia');
INSERT INTO gostade VALUES('Maria','Itália');
INSERT INTO gostade VALUES('Maria','Letônia');
INSERT INTO gostade VALUES('Maria','Liechtenstein');
INSERT INTO gostade VALUES('Maria','Lituânia');
INSERT INTO gostade VALUES('Maria','Luxemburgo');
INSERT INTO gostade VALUES('Maria','Malta');
INSERT INTO gostade VALUES('Maria','Moldávia');
INSERT INTO gostade VALUES('Maria','Mônaco');
INSERT INTO gostade VALUES('Maria','Montenegro');
INSERT INTO gostade VALUES('Maria','Noruega');
INSERT INTO gostade VALUES('Maria','Países Baixos');
INSERT INTO gostade VALUES('Maria','Polônia');
INSERT INTO gostade VALUES('Maria','Portugal');
INSERT INTO gostade VALUES('Maria','República Checa');
INSERT INTO gostade VALUES('Maria','Macedônia do Norte');
INSERT INTO gostade VALUES('Maria','Irlanda do Norte');
INSERT INTO gostade VALUES('Maria','Inglaterra');
INSERT INTO gostade VALUES('Maria','Escócia');
INSERT INTO gostade VALUES('Maria','País de Gales');
INSERT INTO gostade VALUES('Maria','Romênia');
INSERT INTO gostade VALUES('Maria','Rússia');
INSERT INTO gostade VALUES('Maria','San Marinho');
INSERT INTO gostade VALUES('Maria','Sérvia');
INSERT INTO gostade VALUES('Maria','Suécia');
INSERT INTO gostade VALUES('Maria','Suíça');
INSERT INTO gostade VALUES('Maria','Turquia');
INSERT INTO gostade VALUES('Maria','Ucrânia');
INSERT INTO gostade VALUES('Maria','Vaticano');
-- Leonor Likes
INSERT INTO gostade VALUES('Leonor','Albânia');
INSERT INTO gostade VALUES('Leonor','Alemanha');
INSERT INTO gostade VALUES('Leonor','Andorra');
INSERT INTO gostade VALUES('Leonor','Armênia');
INSERT INTO gostade VALUES('Leonor','Áustria');
INSERT INTO gostade VALUES('Leonor','Bélgica');
INSERT INTO gostade VALUES('Leonor','Bielorrúsia');
INSERT INTO gostade VALUES('Leonor','Bósnia e Herzegovina');
INSERT INTO gostade VALUES('Leonor','Bulgária');
INSERT INTO gostade VALUES('Leonor','Chipre');
INSERT INTO gostade VALUES('Leonor','Croátia');
INSERT INTO gostade VALUES('Leonor','Dinamarca');
INSERT INTO gostade VALUES('Leonor','Eslováquia');
INSERT INTO gostade VALUES('Leonor','Eslovênia');
INSERT INTO gostade VALUES('Leonor','Espanha');
INSERT INTO gostade VALUES('Leonor','Estônia');
INSERT INTO gostade VALUES('Leonor','Filândia');
INSERT INTO gostade VALUES('Leonor','França');
INSERT INTO gostade VALUES('Leonor','Grécia');
INSERT INTO gostade VALUES('Leonor','Hungria');
INSERT INTO gostade VALUES('Leonor','Irlanda');
INSERT INTO gostade VALUES('Leonor','Islândia');
INSERT INTO gostade VALUES('Leonor','Itália');
INSERT INTO gostade VALUES('Leonor','Letônia');
INSERT INTO gostade VALUES('Leonor','Liechtenstein');
INSERT INTO gostade VALUES('Leonor','Lituânia');
INSERT INTO gostade VALUES('Leonor','Luxemburgo');
INSERT INTO gostade VALUES('Leonor','Malta');
INSERT INTO gostade VALUES('Leonor','Moldávia');
INSERT INTO gostade VALUES('Leonor','Mônaco');
INSERT INTO gostade VALUES('Leonor','Montenegro');
INSERT INTO gostade VALUES('Leonor','Noruega');
INSERT INTO gostade VALUES('Leonor','Países Baixos');
INSERT INTO gostade VALUES('Leonor','Polônia');
INSERT INTO gostade VALUES('Leonor','Portugal');
INSERT INTO gostade VALUES('Leonor','República Checa');
INSERT INTO gostade VALUES('Leonor','Macedônia do Norte');
INSERT INTO gostade VALUES('Leonor','Irlanda do Norte');
INSERT INTO gostade VALUES('Leonor','Inglaterra');
INSERT INTO gostade VALUES('Leonor','Escócia');
INSERT INTO gostade VALUES('Leonor','País de Gales');
INSERT INTO gostade VALUES('Leonor','Romênia');
INSERT INTO gostade VALUES('Leonor','Rússia');
INSERT INTO gostade VALUES('Leonor','San Marinho');
INSERT INTO gostade VALUES('Leonor','Sérvia');
INSERT INTO gostade VALUES('Leonor','Suécia');
INSERT INTO gostade VALUES('Leonor','Suíça');
INSERT INTO gostade VALUES('Leonor','Turquia');
INSERT INTO gostade VALUES('Leonor','Ucrânia');
INSERT INTO gostade VALUES('Leonor','Vaticano');
-- Guilherme Likes
INSERT INTO gostade VALUES('Guilherme','Albânia');
INSERT INTO gostade VALUES('Guilherme','Alemanha');
INSERT INTO gostade VALUES('Guilherme','Andorra');
INSERT INTO gostade VALUES('Guilherme','Armênia');
INSERT INTO gostade VALUES('Guilherme','Áustria');
INSERT INTO gostade VALUES('Guilherme','Bélgica');
INSERT INTO gostade VALUES('Guilherme','Bielorrúsia');
INSERT INTO gostade VALUES('Guilherme','Bósnia e Herzegovina');
INSERT INTO gostade VALUES('Guilherme','Bulgária');
INSERT INTO gostade VALUES('Guilherme','Chipre');
INSERT INTO gostade VALUES('Guilherme','Croátia');
INSERT INTO gostade VALUES('Guilherme','Dinamarca');
INSERT INTO gostade VALUES('Guilherme','Eslováquia');
INSERT INTO gostade VALUES('Guilherme','Eslovênia');
INSERT INTO gostade VALUES('Guilherme','Espanha');
INSERT INTO gostade VALUES('Guilherme','Estônia');
INSERT INTO gostade VALUES('Guilherme','Filândia');
INSERT INTO gostade VALUES('Guilherme','França');
INSERT INTO gostade VALUES('Guilherme','Grécia');
INSERT INTO gostade VALUES('Guilherme','Hungria');
INSERT INTO gostade VALUES('Guilherme','Irlanda');
INSERT INTO gostade VALUES('Guilherme','Islândia');
INSERT INTO gostade VALUES('Guilherme','Itália');
INSERT INTO gostade VALUES('Guilherme','Letônia');
INSERT INTO gostade VALUES('Guilherme','Liechtenstein');
INSERT INTO gostade VALUES('Guilherme','Lituânia');
INSERT INTO gostade VALUES('Guilherme','Luxemburgo');
INSERT INTO gostade VALUES('Guilherme','Malta');
INSERT INTO gostade VALUES('Guilherme','Moldávia');
INSERT INTO gostade VALUES('Guilherme','Mônaco');
INSERT INTO gostade VALUES('Guilherme','Montenegro');
INSERT INTO gostade VALUES('Guilherme','Noruega');
INSERT INTO gostade VALUES('Guilherme','Países Baixos');
INSERT INTO gostade VALUES('Guilherme','Polônia');
INSERT INTO gostade VALUES('Guilherme','Portugal');
INSERT INTO gostade VALUES('Guilherme','República Checa');
INSERT INTO gostade VALUES('Guilherme','Macedônia do Norte');
INSERT INTO gostade VALUES('Guilherme','Irlanda do Norte');
INSERT INTO gostade VALUES('Guilherme','Inglaterra');
INSERT INTO gostade VALUES('Guilherme','Escócia');
INSERT INTO gostade VALUES('Guilherme','País de Gales');
INSERT INTO gostade VALUES('Guilherme','Romênia');
INSERT INTO gostade VALUES('Guilherme','Rússia');
INSERT INTO gostade VALUES('Guilherme','San Marinho');
INSERT INTO gostade VALUES('Guilherme','Sérvia');
INSERT INTO gostade VALUES('Guilherme','Suécia');
INSERT INTO gostade VALUES('Guilherme','Suíça');
INSERT INTO gostade VALUES('Guilherme','Turquia');
INSERT INTO gostade VALUES('Guilherme','Ucrânia');
INSERT INTO gostade VALUES('Guilherme','Vaticano');
--sILVIA lIKES
INSERT INTO gostade VALUES('Silvia','Albânia');
INSERT INTO gostade VALUES('Silvia','Alemanha');
INSERT INTO gostade VALUES('Silvia','Andorra');
INSERT INTO gostade VALUES('Silvia','Armênia');
INSERT INTO gostade VALUES('Silvia','Áustria');
INSERT INTO gostade VALUES('Silvia','Bélgica');
INSERT INTO gostade VALUES('Silvia','Bielorrúsia');
INSERT INTO gostade VALUES('Silvia','Bósnia e Herzegovina');
INSERT INTO gostade VALUES('Silvia','Bulgária');
INSERT INTO gostade VALUES('Silvia','Chipre');
INSERT INTO gostade VALUES('Silvia','Croátia');
INSERT INTO gostade VALUES('Silvia','Dinamarca');
INSERT INTO gostade VALUES('Silvia','Eslováquia');
INSERT INTO gostade VALUES('Silvia','Eslovênia');
INSERT INTO gostade VALUES('Silvia','Espanha');
INSERT INTO gostade VALUES('Silvia','Estônia');
INSERT INTO gostade VALUES('Silvia','Filândia');
INSERT INTO gostade VALUES('Silvia','França');
INSERT INTO gostade VALUES('Silvia','Grécia');
INSERT INTO gostade VALUES('Silvia','Hungria');
INSERT INTO gostade VALUES('Silvia','Irlanda');
INSERT INTO gostade VALUES('Silvia','Islândia');
INSERT INTO gostade VALUES('Silvia','Itália');
INSERT INTO gostade VALUES('Silvia','Letônia');
INSERT INTO gostade VALUES('Silvia','Liechtenstein');
INSERT INTO gostade VALUES('Silvia','Lituânia');
INSERT INTO gostade VALUES('Silvia','Luxemburgo');
INSERT INTO gostade VALUES('Silvia','Malta');
INSERT INTO gostade VALUES('Silvia','Moldávia');
INSERT INTO gostade VALUES('Silvia','Mônaco');
INSERT INTO gostade VALUES('Silvia','Montenegro');
INSERT INTO gostade VALUES('Silvia','Noruega');
INSERT INTO gostade VALUES('Silvia','Países Baixos');
INSERT INTO gostade VALUES('Silvia','Polônia');
INSERT INTO gostade VALUES('Silvia','Portugal');
INSERT INTO gostade VALUES('Silvia','República Checa');
INSERT INTO gostade VALUES('Silvia','Macedônia do Norte');
INSERT INTO gostade VALUES('Silvia','Irlanda do Norte');
INSERT INTO gostade VALUES('Silvia','Inglaterra');
INSERT INTO gostade VALUES('Silvia','Escócia');
INSERT INTO gostade VALUES('Silvia','País de Gales');
INSERT INTO gostade VALUES('Silvia','Romênia');
INSERT INTO gostade VALUES('Silvia','Rússia');
INSERT INTO gostade VALUES('Silvia','San Marinho');
INSERT INTO gostade VALUES('Silvia','Sérvia');
INSERT INTO gostade VALUES('Silvia','Suécia');
INSERT INTO gostade VALUES('Silvia','Suíça');
INSERT INTO gostade VALUES('Silvia','Turquia');
INSERT INTO gostade VALUES('Silvia','Ucrânia');
INSERT INTO gostade VALUES('Silvia','Vaticano');
