-- Name and Info of Menbers
insert into membro VALUES('Gonçalo','g@hotmail.com',2002);
insert into membro VALUES('Maria','maria@gmail.pt',2001);
insert into membro VALUES('Leonor ','leonor@yahoo.org',1976);
insert into membro VALUES('Guilherme','gui@alunos.uevora.pt',1986);
insert into membro VALUES('Silvia','silvia@frusoal.pt',1976);
insert into membro VALUES('Ricardo','ricardo@eva.motorista.pt',1978);
insert into membro VALUES('Patricia','Pat@live.com.pt',1998);
insert into membro VALUES('Helder','Hell@yahoo.com',1999);
insert into membro VALUES('Daniela','daniela@risco.fidelidade.pt',1999);
insert into membro VALUES('Sandra','sandra.gestora@santander.com',1975);
insert into membro VALUES('Carlos','carlos@piloto.tap.com',1967);
insert into membro VALUES('andre','andre@it.siva.com',1995);
insert into membro VALUES('Visa','visa@algarmanta.pt', 1981);
insert into membro VALUES('Susana','susana@mar&sol.pt',1987);
insert into membro VALUES('Ilidio','ilidio@rentaprtmr.pt',1986);
--Member Gonçalo likes
INSERT INTO gostade VALUES('Gonçalo','Albânia');
INSERT INTO gostade VALUES('Gonçalo','Alemanha');
INSERT INTO gostade VALUES('Gonçalo','Andorra');
INSERT INTO gostade VALUES('Gonçalo','Armênia');
INSERT INTO gostade VALUES('Gonçalo','Áustria');
INSERT INTO gostade VALUES('Gonçalo','Bélgica');
INSERT INTO gostade VALUES('Gonçalo','Bielorrúsia');
INSERT INTO gostade VALUES('Gonçalo','Bósnia e Herzegovina');
INSERT INTO gostade VALUES('Gonçalo','Bulgária');
INSERT INTO gostade VALUES('Gonçalo','Chipre');
INSERT INTO gostade VALUES('Gonçalo','Croátia');
INSERT INTO gostade VALUES('Gonçalo','Dinamarca');
INSERT INTO gostade VALUES('Gonçalo','Eslováquia');
INSERT INTO gostade VALUES('Gonçalo','Eslovênia');
INSERT INTO gostade VALUES('Gonçalo','Espanha');
INSERT INTO gostade VALUES('Gonçalo','Estônia');
INSERT INTO gostade VALUES('Gonçalo','Filândia');
INSERT INTO gostade VALUES('Gonçalo','França');
INSERT INTO gostade VALUES('Gonçalo','Grécia');
INSERT INTO gostade VALUES('Gonçalo','Hungria');
INSERT INTO gostade VALUES('Gonçalo','Irlanda');
INSERT INTO gostade VALUES('Gonçalo','Islândia');
INSERT INTO gostade VALUES('Gonçalo','Itália');
INSERT INTO gostade VALUES('Gonçalo','Letônia');
INSERT INTO gostade VALUES('Gonçalo','Liechtenstein');
INSERT INTO gostade VALUES('Gonçalo','Lituânia');
INSERT INTO gostade VALUES('Gonçalo','Luxemburgo');
INSERT INTO gostade VALUES('Gonçalo','Malta');
INSERT INTO gostade VALUES('Gonçalo','Moldávia');
INSERT INTO gostade VALUES('Gonçalo','Mônaco');
INSERT INTO gostade VALUES('Gonçalo','Montenegro');
INSERT INTO gostade VALUES('Gonçalo','Noruega');
INSERT INTO gostade VALUES('Gonçalo','Países Baixos');
INSERT INTO gostade VALUES('Gonçalo','Polônia');
INSERT INTO gostade VALUES('Gonçalo','Portugal');
INSERT INTO gostade VALUES('Gonçalo','República Checa');
INSERT INTO gostade VALUES('Gonçalo','Macedônia do Norte');
INSERT INTO gostade VALUES('Gonçalo','Irlanda do Norte');
INSERT INTO gostade VALUES('Gonçalo','Inglaterra');
INSERT INTO gostade VALUES('Gonçalo','Escócia');
INSERT INTO gostade VALUES('Gonçalo','País de Gales');
INSERT INTO gostade VALUES('Gonçalo','Romênia');
INSERT INTO gostade VALUES('Gonçalo','Rússia');
INSERT INTO gostade VALUES('Gonçalo','San Marinho');
INSERT INTO gostade VALUES('Gonçalo','Sérvia');
INSERT INTO gostade VALUES('Gonçalo','Suécia');
INSERT INTO gostade VALUES('Gonçalo','Suíça');
INSERT INTO gostade VALUES('Gonçalo','Turquia');
INSERT INTO gostade VALUES('Gonçalo','Ucrânia');
INSERT INTO gostade VALUES('Gonçalo','Vaticano');
